/* MeasureMe question bank.
   q: question · h: hint · u: unit · m: what's measured · k: gauge skin (height | length | temp | other)
   min/max: slider range in u (log: true for ranges spanning orders of magnitude) · a: answer · x: field note */
const ROUNDS = [
  { name: "Calibration", count: 2, pts: 200, blurb: "Things you’ve seen, held or heard of. Warm up the eye.", items: [
    { q: "How tall was Queen Victoria?", h: "Britain’s monarch from 1837 to 1901.", u: "cm", m: "Height", k: "height", min: 130, max: 200, a: 152, x: "About 152 cm, just under 5 ft. Her gowns, preserved in museums, show how petite she was." },
    { q: "How tall is the Statue of Liberty, from her heel to the tip of the torch?", h: "The copper statue only, not the pedestal.", u: "ft", m: "Height", k: "height", min: 0, max: 250, a: 151, x: "151 ft 1 in from heel to torch. With the pedestal and foundation, it’s 305 ft from the ground." },
    { q: "How long is an NFL field, end zones included?", h: "Back line to back line.", u: "yd", m: "Length", k: "length", min: 60, max: 160, a: 120, x: "100 yards of field plus two 10-yard end zones: 120 yards, or 360 ft." },
    { q: "How much does a gallon of water weigh?", h: "One U.S. gallon, at room temperature.", u: "lb", m: "Weight", k: "other", min: 0, max: 15, a: 8.34, x: "About 8.34 lb (3.78 kg), which is why a full 5-gallon jug is such a workout." },
    { q: "What’s the inside temperature of a medium-rare steak?", h: "Measured in the center, after resting.", u: "°F", m: "Temperature", k: "temp", min: 90, max: 200, a: 130, x: "About 130–135°F. Pull it a few degrees early and it coasts up while it rests." },
    { q: "How high is an NBA hoop’s rim?", h: "From the floor to the top of the rim.", u: "ft", m: "Height", k: "height", min: 6, max: 20, a: 10, x: "Exactly 10 ft, a height set in 1891 when James Naismith nailed peach baskets to a gym balcony." },
    { q: "How long is a marathon?", h: "The official road-race distance.", u: "mi", m: "Distance", k: "length", min: 5, max: 50, a: 26.2, x: "26.2 miles (42.195 km). The odd distance comes from the 1908 London Olympics route." },
    { q: "How tall is the Eiffel Tower?", h: "Including its antennas.", u: "m", m: "Height", k: "height", min: 100, max: 500, a: 330, x: "330 m (1,083 ft) with antennas. It grows about 15 cm on hot days as the iron expands." },
    { q: "How heavy is the heaviest legal bowling ball?", h: "The maximum under official rules.", u: "lb", m: "Weight", k: "other", min: 4, max: 30, a: 16, x: "16 lb is the regulation max. Many pros actually throw 14–15 lb balls." },
    { q: "How fast was Usain Bolt at top speed?", h: "During his 9.58-second 100 m world record.", u: "mph", m: "Speed", k: "other", min: 10, max: 50, a: 27.8, x: "Bolt peaked around 27.8 mph (44.7 km/h) between 60 and 80 m of that 2009 race." },
    { q: "How much does a U.S. nickel weigh?", h: "A single 5-cent coin.", u: "g", m: "Weight", k: "other", min: 0, max: 12, a: 5, x: "Exactly 5 grams, so a nickel doubles as a handy calibration weight." },
    { q: "How tall is an adult male giraffe?", h: "Hooves to the tips of its horns.", u: "ft", m: "Height", k: "height", min: 8, max: 25, a: 18, x: "Males reach about 18 ft (5.5 m). Their necks have the same seven vertebrae as ours." },
    { q: "How hot is a Neapolitan pizza oven?", h: "Wood-fired, on the oven floor.", u: "°F", m: "Temperature", k: "temp", min: 400, max: 2000, a: 850, x: "About 800–900°F, which bakes a pizza in 60–90 seconds." },
    { q: "How long is an NBA game, not counting stoppages?", h: "Regulation time, all four quarters.", u: "min", m: "Time", k: "other", min: 20, max: 90, a: 48, x: "Four 12-minute quarters make 48 minutes, though a real game runs over two hours." },
    { q: "How cold should a home freezer be?", h: "The FDA-recommended setting.", u: "°F", m: "Temperature", k: "temp", min: -30, max: 70, a: 0, x: "0°F (−18°C). At that temperature, bacteria stop growing." }
  ]},
  { name: "Field Work", count: 3, pts: 300, blurb: "Landmarks, animals and records you know exist but have never measured.", items: [
    { q: "How long is the main span of the Golden Gate Bridge?", h: "Tower to tower.", u: "ft", m: "Length", k: "length", min: 1000, max: 8000, a: 4200, x: "4,200 ft (1,280 m). It was the world’s longest suspension span when it opened in 1937." },
    { q: "How deep is the deepest point in the ocean?", h: "Challenger Deep, in the Mariana Trench.", u: "m", m: "Depth", k: "length", min: 2000, max: 15000, a: 10935, x: "About 10,935 m (35,876 ft). Drop Everest in and its peak would still be over 2 km underwater." },
    { q: "How tall was Abraham Lincoln?", h: "America’s tallest president.", u: "cm", m: "Height", k: "height", min: 150, max: 220, a: 193, x: "6 ft 4 in (193 cm). With his stovepipe hat, he topped 7 ft." },
    { q: "How tall was Napoleon Bonaparte?", h: "Famous for being “short.”", u: "cm", m: "Height", k: "height", min: 140, max: 200, a: 169, x: "About 169 cm (5 ft 7 in), average for his day. The myth came from French vs. English inches and British cartoons." },
    { q: "How long was the longest blue whale ever measured?", h: "The largest animal known to have lived.", u: "m", m: "Length", k: "length", min: 5, max: 50, a: 29.9, x: "About 29.9 m (98 ft). A blue whale’s heart alone is the size of a small car." },
    { q: "How much does the Hope Diamond weigh?", h: "The famous blue diamond at the Smithsonian.", u: "carats", m: "Weight", k: "other", min: 1, max: 120, a: 45.52, x: "45.52 carats, about 9.1 grams. It was long rumored to be cursed." },
    { q: "How heavy is a fully loaded Boeing 747-400 at takeoff?", h: "Its maximum takeoff weight.", u: "lb", m: "Weight", k: "other", min: 10000, max: 10000000, log: true, a: 875000, x: "About 875,000 lb (397 tonnes). Fuel can be around 40% of that." },
    { q: "How long does sunlight take to reach Earth?", h: "From the Sun’s surface to your face.", u: "min", m: "Time", k: "other", min: 0, max: 30, a: 8.3, x: "About 8 minutes 20 seconds. If the Sun vanished, you wouldn’t know for 8.3 minutes." },
    { q: "How tall is Mount Everest?", h: "Above sea level.", u: "ft", m: "Height", k: "height", min: 10000, max: 45000, a: 29032, x: "29,032 ft (8,849 m), per the 2020 China–Nepal survey. It still grows a few millimeters a year." },
    { q: "How fast can a cheetah run?", h: "The fastest one ever timed.", u: "mph", m: "Speed", k: "other", min: 10, max: 120, a: 61, x: "A cheetah named Sarah hit about 61 mph in 2012, running 100 m in 5.95 seconds." },
    { q: "How hot is fresh lava from Kīlauea?", h: "Hawaiian basalt, glowing orange.", u: "°F", m: "Temperature", k: "temp", min: 500, max: 4000, a: 2120, x: "About 2,120°F (1,160°C). Runny lava like this is hotter than the sticky kind from explosive volcanoes." },
    { q: "How much does an adult human brain weigh?", h: "An average adult.", u: "lb", m: "Weight", k: "other", min: 0, max: 10, a: 3, x: "About 3 lb (1.3–1.4 kg): around 2% of body weight, but about 20% of your energy use." },
    { q: "How long is the Great Wall of China?", h: "Every branch, per China’s 2012 survey.", u: "mi", m: "Length", k: "length", min: 100, max: 100000, log: true, a: 13171, x: "About 13,171 miles (21,196 km), counting every branch built over 2,000 years." },
    { q: "How deep is the deepest hole ever drilled?", h: "The Kola Superdeep Borehole, Russia.", u: "m", m: "Depth", k: "length", min: 1000, max: 20000, a: 12262, x: "12,262 m (7.6 miles). Drilling stopped when the rock hit about 180°C (356°F)." },
    { q: "How high does the International Space Station orbit?", h: "Above Earth’s surface.", u: "mi", m: "Altitude", k: "height", min: 20, max: 1000, a: 250, x: "About 250 miles (400 km). It circles Earth every 90 minutes." },
    { q: "How cold is dry ice?", h: "Frozen carbon dioxide.", u: "°F", m: "Temperature", k: "temp", min: -300, max: 100, a: -109.3, x: "−109.3°F (−78.5°C). It skips liquid entirely and turns straight into gas." },
    { q: "How tall is the Burj Khalifa?", h: "The world’s tallest building, in Dubai.", u: "m", m: "Height", k: "height", min: 200, max: 1500, a: 828, x: "828 m (2,717 ft). You can watch the sunset at the base, ride up, and watch it again." },
    { q: "How long did the shortest war in history last?", h: "Britain vs. Zanzibar, 1896.", u: "min", m: "Time", k: "other", min: 1, max: 10000, log: true, a: 38, x: "About 38 minutes. The Sultan’s palace was shelled until he fled, and Zanzibar surrendered before lunch." },
    { q: "How far away is the Moon?", h: "Its average distance from Earth.", u: "mi", m: "Distance", k: "length", min: 1000, max: 10000000, log: true, a: 238855, x: "About 238,855 miles (384,400 km). Every other planet in the solar system would fit in that gap." }
  ]},
  { name: "Deep Cuts", count: 5, pts: 500, blurb: "Obscure records, strange biology and numbers nobody should know.", items: [
    { q: "How tall was Robert Wadlow, the tallest man ever?", h: "Measured in 1940, shortly before his death.", u: "cm", m: "Height", k: "height", min: 160, max: 320, a: 272, x: "272 cm (8 ft 11.1 in). He was still growing when he died at 22." },
    { q: "How fast does a peregrine falcon dive?", h: "The fastest dive ever recorded.", u: "mph", m: "Speed", k: "other", min: 20, max: 400, a: 242, x: "About 242 mph (389 km/h), making it the fastest animal on Earth." },
    { q: "How long can a giant squid grow?", h: "The longest reliably measured, tentacles included.", u: "m", m: "Length", k: "length", min: 1, max: 30, a: 13, x: "Around 12–13 m (about 43 ft). Its eyes are the size of dinner plates." },
    { q: "How long is one day on Venus?", h: "One full rotation, in Earth days.", u: "days", m: "Time", k: "other", min: 1, max: 1000, log: true, a: 243, x: "243 Earth days, longer than its year (225 days). It also spins backward." },
    { q: "How tall is Olympus Mons, the great volcano on Mars?", h: "The biggest volcano in the solar system.", u: "ft", m: "Height", k: "height", min: 10000, max: 150000, a: 72000, x: "About 72,000 ft (22 km), roughly 2.5 times the height of Everest." },
    { q: "How fast do your fingernails grow?", h: "Average growth per month.", u: "mm/mo", m: "Growth", k: "other", min: 0.1, max: 100, log: true, a: 3.5, x: "About 3.5 mm a month. Toenails grow roughly a third as fast." },
    { q: "How wide was the largest hailstone ever recorded in the U.S.?", h: "Vivian, South Dakota, 2010.", u: "in", m: "Diameter", k: "length", min: 0, max: 20, a: 8, x: "8 inches across and almost 2 lb. The man who found it kept it in his freezer." },
    { q: "How long was the longest domestic cat ever measured?", h: "Nose to tail tip, per Guinness.", u: "in", m: "Length", k: "length", min: 10, max: 100, a: 48.5, x: "48.5 inches: a Maine Coon named Stewie, measured in 2010." },
    { q: "How deep does the Titanic lie?", h: "Below the North Atlantic’s surface.", u: "ft", m: "Depth", k: "length", min: 1000, max: 30000, a: 12500, x: "About 12,500 ft (3,800 m). The wreck wasn’t found until 1985." },
    { q: "How fast was the fastest tennis serve ever recorded?", h: "Sam Groth, 2012.", u: "mph", m: "Speed", k: "other", min: 50, max: 250, a: 163.7, x: "163.7 mph (263 km/h), at a Challenger tournament in Busan, South Korea." },
    { q: "How hot is the bubble from a pistol shrimp’s snap?", h: "Right as the bubble collapses.", u: "°F", m: "Temperature", k: "temp", min: 100, max: 20000, a: 8500, x: "About 8,500°F, close to the Sun’s surface, for a split second. It even flashes light." },
    { q: "How tall is the world’s tallest known tree?", h: "Hyperion, a coast redwood in California.", u: "ft", m: "Height", k: "height", min: 100, max: 600, a: 380, x: "About 380 ft (116 m). Its exact location is kept secret to protect it." },
    { q: "How long did the longest attack of hiccups last?", h: "Charles Osborne of Iowa.", u: "years", m: "Time", k: "other", min: 0, max: 100, a: 68, x: "68 years, from 1922 to 1990. He still married twice and had eight children." },
    { q: "How loud is a blue whale’s call?", h: "The loudest sound made by any animal.", u: "dB", m: "Loudness", k: "other", min: 40, max: 250, a: 188, x: "Up to about 188 dB underwater, carrying for hundreds of miles. (Underwater decibels don’t compare directly to decibels in air.)" },
    { q: "How long is the DNA in one human cell, stretched out?", h: "All 46 chromosomes, end to end.", u: "m", m: "Length", k: "length", min: 0.001, max: 1000, log: true, a: 2, x: "About 2 m (6.5 ft), packed into a nucleus a few thousandths of a millimeter wide." },
    { q: "How thick is a human hair?", h: "A typical strand.", u: "µm", m: "Thickness", k: "length", min: 1, max: 10000, log: true, a: 70, x: "About 70 micrometers (0.07 mm), though hair ranges from roughly 17 to 180." },
    { q: "How cold can a hibernating arctic ground squirrel’s body get?", h: "Deep in winter torpor.", u: "°F", m: "Temperature", k: "temp", min: -20, max: 110, a: 26.8, x: "About 26.8°F (−2.9°C), below freezing, yet its blood stays liquid by supercooling." }
  ]}
];
