/* MeasureMe question bank.
   q: question · h: hint · u: unit · m: what's measured · k: gauge skin (height | length | temp | other)
   log: true for answers best guessed by order of magnitude · a: answer · x: field note
   Gauge ranges are generated from the answer in app.js (see view()). */
const ROUNDS = [
  { name: "Calibration", count: 2, blurb: "Things you’ve seen, held or heard of. Warm up the eye.", items: [
    { q: "How tall was Queen Victoria?", h: "Britain’s monarch from 1837 to 1901.", u: "cm", m: "Height", k: "height", a: 152, x: "About 152 cm, just under 5 ft. Her gowns, preserved in museums, show how petite she was." },
    { q: "How tall is the Statue of Liberty, from her heel to the tip of the torch?", h: "The copper statue only, not the pedestal.", u: "ft", m: "Height", k: "height", a: 151, x: "151 ft 1 in from heel to torch. With the pedestal and foundation, it’s 305 ft from the ground." },
    { q: "How long is an NFL field, end zones included?", h: "Back line to back line.", u: "yd", m: "Length", k: "length", a: 120, x: "100 yards of field plus two 10-yard end zones: 120 yards, or 360 ft." },
    { q: "How much does a gallon of water weigh?", h: "One U.S. gallon, at room temperature.", u: "lb", m: "Weight", k: "other", a: 8.34, x: "About 8.34 lb (3.78 kg), which is why a full 5-gallon jug is such a workout." },
    { q: "What’s the inside temperature of a medium-rare steak?", h: "Measured in the center, after resting.", u: "°F", m: "Temperature", k: "temp", a: 130, x: "About 130–135°F. Pull it a few degrees early and it coasts up while it rests." },
    { q: "How high is an NBA hoop’s rim?", h: "From the floor to the top of the rim.", u: "ft", m: "Height", k: "height", a: 10, x: "Exactly 10 ft, a height set in 1891 when James Naismith nailed peach baskets to a gym balcony." },
    { q: "How long is a marathon?", h: "The official road-race distance.", u: "mi", m: "Distance", k: "length", a: 26.2, x: "26.2 miles (42.195 km). The odd distance comes from the 1908 London Olympics route." },
    { q: "How tall is the Eiffel Tower?", h: "Including its antennas.", u: "m", m: "Height", k: "height", a: 330, x: "330 m (1,083 ft) with antennas. It grows about 15 cm on hot days as the iron expands." },
    { q: "How heavy is the heaviest legal bowling ball?", h: "The maximum under official rules.", u: "lb", m: "Weight", k: "other", a: 16, x: "16 lb is the regulation max. Many pros actually throw 14–15 lb balls." },
    { q: "How fast was Usain Bolt at top speed?", h: "During his 9.58-second 100 m world record.", u: "mph", m: "Speed", k: "other", a: 27.8, x: "Bolt peaked around 27.8 mph (44.7 km/h) between 60 and 80 m of that 2009 race." },
    { q: "How much does a U.S. nickel weigh?", h: "A single 5-cent coin.", u: "g", m: "Weight", k: "other", a: 5, x: "Exactly 5 grams, so a nickel doubles as a handy calibration weight." },
    { q: "How tall is an adult male giraffe?", h: "Hooves to the tips of its horns.", u: "ft", m: "Height", k: "height", a: 18, x: "Males reach about 18 ft (5.5 m). Their necks have the same seven vertebrae as ours." },
    { q: "How hot is a Neapolitan pizza oven?", h: "Wood-fired, on the oven floor.", u: "°F", m: "Temperature", k: "temp", a: 850, x: "About 800–900°F, which bakes a pizza in 60–90 seconds." },
    { q: "How long is an NBA game, not counting stoppages?", h: "Regulation time, all four quarters.", u: "min", m: "Time", k: "other", a: 48, x: "Four 12-minute quarters make 48 minutes, though a real game runs over two hours." },
    { q: "How cold should a home freezer be?", h: "The FDA-recommended setting.", u: "°F", m: "Temperature", k: "temp", a: 0, x: "0°F (−18°C). At that temperature, bacteria stop growing." },
    { q: "How tall is a standard interior door in the U.S.?", h: "Floor to the top of the door itself.", u: "in", m: "Height", k: "height", a: 80, x: "80 inches (6 ft 8 in) is the U.S. standard, which is why very tall people duck." },
    { q: "How tall is an Oscar statuette?", h: "The Academy Award trophy.", u: "in", m: "Height", k: "height", a: 13.5, x: "13.5 inches tall and 8.5 lb, made of bronze plated in 24-karat gold." },
    { q: "How long is an Olympic swimming pool?", h: "One length, end to end.", u: "m", m: "Length", k: "length", a: 50, x: "50 m long and 25 m wide, holding about 2.5 million liters of water." },
    { q: "How long can an MLB bat be?", h: "The maximum length allowed.", u: "in", m: "Length", k: "length", a: 42, x: "42 inches is the limit, though most players swing bats of 33–35 inches." },
    { q: "How far apart are the bases in baseball?", h: "Home to first, first to second, and so on.", u: "ft", m: "Distance", k: "length", a: 90, x: "90 ft. The spacing has barely changed since the 1840s, and it makes infield plays razor close." },
    { q: "How far is the pitcher’s rubber from home plate?", h: "Major League Baseball.", u: "ft", m: "Distance", k: "length", a: 60.5, x: "60 ft 6 in, set in 1893. The odd half foot is often blamed on a misread survey." },
    { q: "How high is a tennis net at its center?", h: "At the middle, not the posts.", u: "in", m: "Height", k: "height", a: 36, x: "36 inches (3 ft) at the center, rising to 3 ft 6 in at the posts." },
    { q: "How wide is a regulation soccer goal?", h: "Post to post, inside edges.", u: "ft", m: "Width", k: "length", a: 24, x: "24 ft (8 yards) wide and 8 ft tall." },
    { q: "How long is an NHL hockey rink?", h: "Board to board, end to end.", u: "ft", m: "Length", k: "length", a: 200, x: "200 ft long and 85 ft wide." },
    { q: "How wide is the hole on a golf green?", h: "The cup’s diameter.", u: "in", m: "Diameter", k: "length", a: 4.25, x: "4.25 inches, a size that dates to a tool used at Musselburgh, Scotland, in 1829." },
    { q: "How long is a bowling lane?", h: "From the foul line to the head pin.", u: "ft", m: "Length", k: "length", a: 60, x: "60 ft from the foul line to the center of the head pin." },
    { q: "How long is a soccer match, not counting stoppage time?", h: "Regulation time, both halves.", u: "min", m: "Time", k: "other", a: 90, x: "Two 45-minute halves, plus whatever stoppage time the referee adds." },
    { q: "How tall is a standard kitchen counter?", h: "Floor to countertop, U.S. standard.", u: "in", m: "Height", k: "height", a: 36, x: "36 inches, set decades ago as a comfortable working height for most adults." },
    { q: "How long is a credit card?", h: "The standard card size.", u: "in", m: "Length", k: "length", a: 3.37, x: "85.6 mm (3.37 in), set by the ISO/IEC 7810 standard, the same as most ID cards." },
    { q: "How much does a U.S. dollar bill weigh?", h: "Any denomination.", u: "g", m: "Weight", k: "other", a: 1, x: "About 1 gram, so a pound of bills is roughly 454 of them." },
    { q: "How long is a U.S. dollar bill?", h: "Edge to edge, the long way.", u: "in", m: "Length", k: "length", a: 6.14, x: "6.14 inches long and 2.61 inches tall." },
    { q: "How tall are the letters of the Hollywood Sign?", h: "Each letter, in the Hollywood Hills.", u: "ft", m: "Height", k: "height", a: 45, x: "45 ft tall, spread across a sign about 350 ft long." },
    { q: "How wide is a U.S. king-size mattress?", h: "Side to side.", u: "in", m: "Width", k: "length", a: 76, x: "76 inches wide and 80 inches long." },
    { q: "How much does a newborn baby weigh?", h: "A typical full-term baby.", u: "lb", m: "Weight", k: "other", a: 7.5, x: "About 7.5 lb (3.4 kg); the U.S. average is close to 7 lb 5 oz." },
    { q: "How long is a newborn baby?", h: "Head to heel, full term.", u: "in", m: "Length", k: "length", a: 20, x: "About 20 inches (51 cm)." },
    { q: "What temperature do most cookie recipes bake at?", h: "The classic oven setting.", u: "°F", m: "Temperature", k: "temp", a: 350, x: "350°F (177°C) is the default for most cookies and cakes." },
    { q: "How much does an NBA basketball weigh?", h: "The official game ball.", u: "oz", m: "Weight", k: "other", a: 22, x: "22 ounces (about 624 g)." },
    { q: "How much can a golf ball weigh?", h: "The maximum under the rules.", u: "oz", m: "Weight", k: "other", a: 1.62, x: "1.62 ounces (45.93 g) at most." },
    { q: "How far is the NBA three-point line at the top of the arc?", h: "From the center of the basket.", u: "ft", m: "Distance", k: "length", a: 23.75, x: "23 ft 9 in at the top, shrinking to 22 ft in the corners." },
    { q: "How long is a new, unsharpened pencil?", h: "A standard wooden pencil.", u: "in", m: "Length", k: "length", a: 7.5, x: "About 7.5 inches. One pencil can draw a line roughly 35 miles long." },
    { q: "How much does a gallon of gasoline weigh?", h: "One U.S. gallon.", u: "lb", m: "Weight", k: "other", a: 6.3, x: "About 6.3 lb, lighter than a gallon of water." },
    { q: "How long is an NFL football?", h: "Tip to tip.", u: "in", m: "Length", k: "length", a: 11, x: "About 11 inches, per the official 11–11.25 inch spec." },
    { q: "How wide is a standard U.S. stop sign?", h: "The usual size on ordinary roads.", u: "in", m: "Width", k: "length", a: 30, x: "30 inches across; highways use larger 36- and 48-inch versions." },
    { q: "How long is a typical U.S. parking space?", h: "A standard spot in a lot.", u: "ft", m: "Length", k: "length", a: 18, x: "About 18 ft long and 9 ft wide." },
    { q: "How tall is Seattle’s Space Needle?", h: "Built for the 1962 World’s Fair.", u: "ft", m: "Height", k: "height", a: 605, x: "605 ft (184 m). It was the tallest structure west of the Mississippi when it opened." },
    { q: "How tall is the Washington Monument?", h: "The obelisk in Washington, D.C.", u: "ft", m: "Height", k: "height", a: 555, x: "About 555 ft, still the world’s tallest stone structure." },
    { q: "How fast does a typical airliner cruise?", h: "A jet at cruising altitude.", u: "mph", m: "Speed", k: "other", a: 575, x: "About 550–600 mph (roughly 900 km/h)." },
    { q: "How long is an NBA court?", h: "Baseline to baseline.", u: "ft", m: "Length", k: "length", a: 94, x: "94 ft long and 50 ft wide." },
    { q: "How long is one lap of an Olympic running track?", h: "Measured in the inside lane.", u: "m", m: "Distance", k: "length", a: 400, x: "400 m in lane 1; outer lanes are longer, which is why starts are staggered." },
    { q: "How hot is a hot tub at its recommended max?", h: "U.S. safety guidance.", u: "°F", m: "Temperature", k: "temp", a: 104, x: "The CPSC says never exceed 104°F (40°C)." },
    { q: "How hot is the air in a Finnish sauna?", h: "Upper bench, dry heat.", u: "°F", m: "Temperature", k: "temp", a: 175, x: "Usually 160–195°F. Dry air lets sweat evaporate and cool you." },
    { q: "How hot is drip coffee right out of the machine?", h: "Poured, not yet sipped.", u: "°F", m: "Temperature", k: "temp", a: 180, x: "Around 175–185°F; the brewing water itself runs 195–205°F." },
    { q: "How hot is deep-fryer oil for fries?", h: "The second, crispy fry.", u: "°F", m: "Temperature", k: "temp", a: 375, x: "About 350–375°F. Cooler oil makes greasy fries." },
    { q: "How hot is a clothes iron on the cotton setting?", h: "The soleplate.", u: "°F", m: "Temperature", k: "temp", a: 400, x: "About 400°F; silk settings sit near 300°F." },
    { q: "How cold should the inside of your fridge be?", h: "The food-safety sweet spot.", u: "°F", m: "Temperature", k: "temp", a: 37, x: "About 37°F: under 40°F slows bacteria, without freezing your lettuce." },
    { q: "When is chicken officially safe to eat?", h: "USDA internal temperature.", u: "°F", m: "Temperature", k: "temp", a: 165, x: "165°F (74°C) kills salmonella instantly." },
    { q: "How cold is the ice at a hockey rink?", h: "Game-ready, at the surface.", u: "°F", m: "Temperature", k: "temp", a: 22, x: "About 16–24°F; colder ice is harder and faster." },
    { q: "How cold is a gym’s cold plunge tub?", h: "The one people post about.", u: "°F", m: "Temperature", k: "temp", a: 50, x: "Usually around 50°F, give or take 10 degrees." },
    { q: "What temperature should red wine be served at?", h: "What a sommelier would pour.", u: "°F", m: "Temperature", k: "temp", a: 62, x: "About 60–65°F, cooler than most living rooms." },
    { q: "How cold is ice cream in a shop’s scooping cabinet?", h: "The tubs behind the glass.", u: "°F", m: "Temperature", k: "temp", a: 8, x: "About 6–10°F, warmer than a home freezer so it scoops easily." }
  ]},
  { name: "Field Work", count: 2, blurb: "Landmarks, animals and records you know exist but have never measured.", items: [
    { q: "How long is the main span of the Golden Gate Bridge?", h: "Tower to tower.", u: "ft", m: "Length", k: "length", a: 4200, x: "4,200 ft (1,280 m). It was the world’s longest suspension span when it opened in 1937." },
    { q: "How deep is the deepest point in the ocean?", h: "Challenger Deep, in the Mariana Trench.", u: "m", m: "Depth", k: "length", a: 10935, x: "About 10,935 m (35,876 ft). Drop Everest in and its peak would still be over 2 km underwater." },
    { q: "How tall was Abraham Lincoln?", h: "America’s tallest president.", u: "cm", m: "Height", k: "height", a: 193, x: "6 ft 4 in (193 cm). With his stovepipe hat, he topped 7 ft." },
    { q: "How tall was Napoleon Bonaparte?", h: "Famous for being “short.”", u: "cm", m: "Height", k: "height", a: 169, x: "About 169 cm (5 ft 7 in), average for his day. The myth came from French vs. English inches and British cartoons." },
    { q: "How long was the longest blue whale ever measured?", h: "The largest animal known to have lived.", u: "m", m: "Length", k: "length", a: 29.9, x: "About 29.9 m (98 ft). A blue whale’s heart alone is the size of a small car." },
    { q: "How much does the Hope Diamond weigh?", h: "The famous blue diamond at the Smithsonian.", u: "carats", m: "Weight", k: "other", a: 45.52, x: "45.52 carats, about 9.1 grams. It was long rumored to be cursed." },
    { q: "How heavy is a fully loaded Boeing 747-400 at takeoff?", h: "Its maximum takeoff weight.", u: "lb", m: "Weight", k: "other", log: true, a: 875000, x: "About 875,000 lb (397 tonnes). Fuel can be around 40% of that." },
    { q: "How long does sunlight take to reach Earth?", h: "From the Sun’s surface to your face.", u: "min", m: "Time", k: "other", a: 8.3, x: "About 8 minutes 20 seconds. If the Sun vanished, you wouldn’t know for 8.3 minutes." },
    { q: "How tall is Mount Everest?", h: "Above sea level.", u: "ft", m: "Height", k: "height", a: 29032, x: "29,032 ft (8,849 m), per the 2020 China–Nepal survey. It still grows a few millimeters a year." },
    { q: "How fast can a cheetah run?", h: "The fastest one ever timed.", u: "mph", m: "Speed", k: "other", a: 61, x: "A cheetah named Sarah hit about 61 mph in 2012, running 100 m in 5.95 seconds." },
    { q: "How hot is fresh lava from Kīlauea?", h: "Hawaiian basalt, glowing orange.", u: "°F", m: "Temperature", k: "temp", a: 2120, x: "About 2,120°F (1,160°C). Runny lava like this is hotter than the sticky kind from explosive volcanoes." },
    { q: "How much does an adult human brain weigh?", h: "An average adult.", u: "lb", m: "Weight", k: "other", a: 3, x: "About 3 lb (1.3–1.4 kg): around 2% of body weight, but about 20% of your energy use." },
    { q: "How long is the Great Wall of China?", h: "Every branch, per China’s 2012 survey.", u: "mi", m: "Length", k: "length", log: true, a: 13171, x: "About 13,171 miles (21,196 km), counting every branch built over 2,000 years." },
    { q: "How deep is the deepest hole ever drilled?", h: "The Kola Superdeep Borehole, Russia.", u: "m", m: "Depth", k: "length", a: 12262, x: "12,262 m (7.6 miles). Drilling stopped when the rock hit about 180°C (356°F)." },
    { q: "How high does the International Space Station orbit?", h: "Above Earth’s surface.", u: "mi", m: "Altitude", k: "height", a: 250, x: "About 250 miles (400 km). It circles Earth every 90 minutes." },
    { q: "How cold is dry ice?", h: "Frozen carbon dioxide.", u: "°F", m: "Temperature", k: "temp", a: -109.3, x: "−109.3°F (−78.5°C). It skips liquid entirely and turns straight into gas." },
    { q: "How tall is the Burj Khalifa?", h: "The world’s tallest building, in Dubai.", u: "m", m: "Height", k: "height", a: 828, x: "828 m (2,717 ft). You can watch the sunset at the base, ride up, and watch it again." },
    { q: "How long did the shortest war in history last?", h: "Britain vs. Zanzibar, 1896.", u: "min", m: "Time", k: "other", log: true, a: 38, x: "About 38 minutes. The Sultan’s palace was shelled until he fled, and Zanzibar surrendered before lunch." },
    { q: "How far away is the Moon?", h: "Its average distance from Earth.", u: "mi", m: "Distance", k: "length", log: true, a: 238855, x: "About 238,855 miles (384,400 km). Every other planet in the solar system would fit in that gap." },
    { q: "How long is the main span of the Brooklyn Bridge?", h: "Between its two stone towers.", u: "ft", m: "Length", k: "length", a: 1595.5, x: "1,595.5 ft. When it opened in 1883 it was the longest suspension bridge in the world." },
    { q: "How tall is Big Ben’s tower?", h: "The Elizabeth Tower in London.", u: "ft", m: "Height", k: "height", a: 316, x: "About 316 ft (96 m). Big Ben is technically the bell, not the tower." },
    { q: "What’s the wingspan of a Boeing 747-400?", h: "Wingtip to wingtip.", u: "ft", m: "Width", k: "length", a: 211, x: "About 211 ft (64.4 m), wider than the Wright brothers’ first flight was long." },
    { q: "How tall is the Gateway Arch in St. Louis?", h: "Ground to the top of the arch.", u: "ft", m: "Height", k: "height", a: 630, x: "630 ft, and it’s exactly as wide at its base as it is tall." },
    { q: "How fast does sound travel through air?", h: "At sea level, on a mild day.", u: "mph", m: "Speed", k: "other", a: 767, x: "About 767 mph (343 m/s) at 68°F. Count seconds after lightning and divide by 5 for miles." },
    { q: "How long is the island of Manhattan?", h: "Its full north-to-south length.", u: "mi", m: "Length", k: "length", a: 13.4, x: "About 13.4 miles long and only 2.3 miles across at its widest." },
    { q: "How deep is the Grand Canyon at its deepest?", h: "From the rim to the Colorado River.", u: "ft", m: "Depth", k: "length", a: 6000, x: "About 6,000 ft (1.8 km), exposing nearly 2 billion years of rock." },
    { q: "How tall is each face on Mount Rushmore?", h: "Chin to top of the head.", u: "ft", m: "Height", k: "height", a: 60, x: "About 60 ft. Washington’s nose alone is around 20 ft long." },
    { q: "How long is Lake Michigan?", h: "North to south.", u: "mi", m: "Length", k: "length", a: 307, x: "About 307 miles long, the only Great Lake entirely inside the U.S." },
    { q: "How long is the Nile River?", h: "From its farthest source to the Mediterranean.", u: "mi", m: "Length", k: "length", a: 4130, x: "About 4,130 miles (6,650 km), usually ranked as the world’s longest river." },
    { q: "How long is the Panama Canal?", h: "Atlantic to Pacific.", u: "mi", m: "Length", k: "length", a: 51, x: "About 51 miles (82 km). A ship takes roughly 8–10 hours to cross." },
    { q: "How tall was the Great Pyramid of Giza when it was finished?", h: "Before its capstone and casing were lost.", u: "ft", m: "Height", k: "height", a: 481, x: "About 481 ft (146.6 m). It was the tallest human-made structure for nearly 4,000 years." },
    { q: "How tall is the Christ the Redeemer statue?", h: "The statue in Rio, not its pedestal.", u: "ft", m: "Height", k: "height", a: 98, x: "About 98 ft (30 m), with arms spanning about 92 ft." },
    { q: "How far away is the horizon when you stand on a beach?", h: "An adult looking out at the ocean.", u: "mi", m: "Distance", k: "length", a: 3, x: "About 3 miles. Climb higher and it stretches fast." },
    { q: "How tall is the Leaning Tower of Pisa?", h: "Measured on its higher side.", u: "ft", m: "Height", k: "height", a: 186, x: "About 186 ft. It leans about 4 degrees, less than it did before engineers stabilized it." },
    { q: "How long is one lap of Daytona International Speedway?", h: "The famous oval.", u: "mi", m: "Distance", k: "length", a: 2.5, x: "2.5 miles, so the Daytona 500 is 200 laps." },
    { q: "How tall is the Hoover Dam?", h: "From bedrock to the top.", u: "ft", m: "Height", k: "height", a: 726, x: "726 ft, with enough concrete to pave a two-lane road from San Francisco to New York." },
    { q: "How fast does the ground at the equator spin with the Earth?", h: "Earth’s rotation at its widest point.", u: "mph", m: "Speed", k: "other", a: 1037, x: "About 1,037 mph (1,670 km/h), and you never feel a thing." },
    { q: "How fast is the world’s fastest roller coaster?", h: "Formula Rossa, Abu Dhabi.", u: "mph", m: "Speed", k: "other", a: 149.1, x: "149.1 mph (240 km/h), reached in under 5 seconds. Riders wear goggles." },
    { q: "How fast do Japan’s fastest bullet trains run in service?", h: "Top speed with passengers.", u: "km/h", m: "Speed", k: "other", a: 320, x: "320 km/h (about 199 mph) on the Tōhoku Shinkansen." },
    { q: "How old was the oldest person ever verified?", h: "Jeanne Calment of France.", u: "years", m: "Age", k: "other", a: 122, x: "122 years and 164 days. She met Vincent van Gogh as a teenager." },
    { q: "How wide is the Earth?", h: "Its diameter at the equator.", u: "mi", m: "Diameter", k: "length", a: 7918, x: "About 7,918 miles (12,742 km)." },
    { q: "How wide is the Moon?", h: "Its diameter.", u: "mi", m: "Diameter", k: "length", a: 2159, x: "About 2,159 miles (3,475 km), just over a quarter of Earth’s width." },
    { q: "How far is Earth from the Sun?", h: "The average distance.", u: "mi", m: "Distance", k: "length", log: true, a: 93000000, x: "About 93 million miles (150 million km), which is called one astronomical unit." },
    { q: "At what temperature does iron melt?", h: "Pure iron.", u: "°F", m: "Temperature", k: "temp", a: 2800, x: "About 2,800°F (1,538°C)." },
    { q: "At what temperature does gold melt?", h: "Pure 24-karat gold.", u: "°F", m: "Temperature", k: "temp", a: 1948, x: "1,948°F (1,064°C), which is why jewelers need torches, not stoves." },
    { q: "How hot is a lightning bolt?", h: "The air inside the channel.", u: "°F", m: "Temperature", k: "temp", a: 50000, x: "About 50,000°F, roughly five times hotter than the Sun’s surface, for a few microseconds." },
    { q: "How long is one year on Neptune?", h: "One trip around the Sun, in Earth years.", u: "years", m: "Time", k: "other", a: 165, x: "About 165 Earth years. It completed its first full orbit since its discovery in 2011." },
    { q: "How long is an African elephant’s pregnancy?", h: "The longest of any mammal.", u: "months", m: "Time", k: "other", a: 22, x: "About 22 months, and the calf weighs around 250 lb at birth." },
    { q: "How long did the Hundred Years’ War last?", h: "England vs. France.", u: "years", m: "Time", k: "other", a: 116, x: "116 years, from 1337 to 1453, with long truces in between." },
    { q: "How old is the universe?", h: "Time since the Big Bang.", u: "billion yr", m: "Age", k: "other", a: 13.8, x: "About 13.8 billion years, measured from the cosmic microwave background." },
    { q: "How long ago did the non-bird dinosaurs die out?", h: "The asteroid impact.", u: "million yr", m: "Time", k: "other", a: 66, x: "About 66 million years ago, when an asteroid struck near today’s Yucatán Peninsula." },
    { q: "How long was a Tyrannosaurus rex?", h: "Nose to tail, a big adult.", u: "ft", m: "Length", k: "length", a: 40, x: "About 40 ft. The famous skeleton named Sue measures 40.5 ft." },
    { q: "How wide can a wandering albatross’s wings stretch?", h: "Wingtip to wingtip.", u: "ft", m: "Wingspan", k: "length", a: 11, x: "Up to about 11 ft (3.4 m), the widest of any living bird." },
    { q: "How long was the Titanic?", h: "Bow to stern.", u: "ft", m: "Length", k: "length", a: 882.75, x: "882 ft 9 in, about as long as three football fields." },
    { q: "How tall is an emperor penguin?", h: "An adult, standing.", u: "in", m: "Height", k: "height", a: 45, x: "About 45 inches (115 cm), the tallest penguin alive." },
    { q: "How long is a giraffe’s tongue?", h: "Fully extended.", u: "in", m: "Length", k: "length", a: 20, x: "Up to about 20 inches, dark purple, and tough enough to strip thorny acacia branches." },
    { q: "How long is an adult male sperm whale?", h: "The largest toothed animal.", u: "ft", m: "Length", k: "length", a: 52, x: "About 52 ft (16 m), with the biggest brain of any animal." },
    { q: "How hard does the atmosphere press on you at sea level?", h: "Air pressure per square inch.", u: "psi", m: "Pressure", k: "other", a: 14.7, x: "About 14.7 psi, or roughly a ton on every square foot." },
    { q: "How hot is the surface of Venus?", h: "Any time of day, anywhere.", u: "°F", m: "Temperature", k: "temp", a: 867, x: "About 867°F, hotter than Mercury thanks to a runaway greenhouse effect." },
    { q: "How cold is liquid nitrogen?", h: "Boiling in an open flask.", u: "°F", m: "Temperature", k: "temp", a: -320.4, x: "−320.4°F (−196°C), its boiling point at sea level." },
    { q: "How hot is the hottest part of a candle flame?", h: "Not the bright yellow part.", u: "°F", m: "Temperature", k: "temp", a: 2550, x: "About 2,550°F (1,400°C), in the faint blue zone near the wick." },
    { q: "How hot is the surface of the Sun?", h: "The visible surface, or photosphere.", u: "°F", m: "Temperature", k: "temp", a: 10000, x: "About 10,000°F (5,500°C)." },
    { q: "How much does an ostrich egg weigh?", h: "The largest egg of any living bird.", u: "lb", m: "Weight", k: "other", a: 3, x: "About 3 lb (1.4 kg), equal to roughly two dozen chicken eggs." },
    { q: "How much does a ruby-throated hummingbird weigh?", h: "A typical adult.", u: "g", m: "Weight", k: "other", a: 3, x: "About 3 grams, less than a nickel." }
  ]},
  { name: "Deep Cuts", count: 1, blurb: "Obscure records, strange biology and numbers nobody should know.", items: [
    { q: "How tall was Robert Wadlow, the tallest man ever?", h: "Measured in 1940, shortly before his death.", u: "cm", m: "Height", k: "height", a: 272, x: "272 cm (8 ft 11.1 in). He was still growing when he died at 22." },
    { q: "How fast does a peregrine falcon dive?", h: "The fastest dive ever recorded.", u: "mph", m: "Speed", k: "other", a: 242, x: "About 242 mph (389 km/h), making it the fastest animal on Earth." },
    { q: "How long can a giant squid grow?", h: "The longest reliably measured, tentacles included.", u: "m", m: "Length", k: "length", a: 13, x: "Around 12–13 m (about 43 ft). Its eyes are the size of dinner plates." },
    { q: "How long is one day on Venus?", h: "One full rotation, in Earth days.", u: "days", m: "Time", k: "other", log: true, a: 243, x: "243 Earth days, longer than its year (225 days). It also spins backward." },
    { q: "How tall is Olympus Mons, the great volcano on Mars?", h: "The biggest volcano in the solar system.", u: "ft", m: "Height", k: "height", a: 72000, x: "About 72,000 ft (22 km), roughly 2.5 times the height of Everest." },
    { q: "How fast do your fingernails grow?", h: "Average growth per month.", u: "mm/mo", m: "Growth", k: "other", log: true, a: 3.5, x: "About 3.5 mm a month. Toenails grow roughly a third as fast." },
    { q: "How wide was the largest hailstone ever recorded in the U.S.?", h: "Vivian, South Dakota, 2010.", u: "in", m: "Diameter", k: "length", a: 8, x: "8 inches across and almost 2 lb. The man who found it kept it in his freezer." },
    { q: "How long was the longest domestic cat ever measured?", h: "Nose to tail tip, per Guinness.", u: "in", m: "Length", k: "length", a: 48.5, x: "48.5 inches: a Maine Coon named Stewie, measured in 2010." },
    { q: "How deep does the Titanic lie?", h: "Below the North Atlantic’s surface.", u: "ft", m: "Depth", k: "length", a: 12500, x: "About 12,500 ft (3,800 m). The wreck wasn’t found until 1985." },
    { q: "How fast was the fastest tennis serve ever recorded?", h: "Sam Groth, 2012.", u: "mph", m: "Speed", k: "other", a: 163.7, x: "163.7 mph (263 km/h), at a Challenger tournament in Busan, South Korea." },
    { q: "How hot is the bubble from a pistol shrimp’s snap?", h: "Right as the bubble collapses.", u: "°F", m: "Temperature", k: "temp", a: 8500, x: "About 8,500°F, close to the Sun’s surface, for a split second. It even flashes light." },
    { q: "How tall is the world’s tallest known tree?", h: "Hyperion, a coast redwood in California.", u: "ft", m: "Height", k: "height", a: 380, x: "About 380 ft (116 m). Its exact location is kept secret to protect it." },
    { q: "How long did the longest attack of hiccups last?", h: "Charles Osborne of Iowa.", u: "years", m: "Time", k: "other", a: 68, x: "68 years, from 1922 to 1990. He still married twice and had eight children." },
    { q: "How loud is a blue whale’s call?", h: "The loudest sound made by any animal.", u: "dB", m: "Loudness", k: "other", a: 188, x: "Up to about 188 dB underwater, carrying for hundreds of miles. (Underwater decibels don’t compare directly to decibels in air.)" },
    { q: "How long is the DNA in one human cell, stretched out?", h: "All 46 chromosomes, end to end.", u: "m", m: "Length", k: "length", log: true, a: 2, x: "About 2 m (6.5 ft), packed into a nucleus a few thousandths of a millimeter wide." },
    { q: "How thick is a human hair?", h: "A typical strand.", u: "µm", m: "Thickness", k: "length", log: true, a: 70, x: "About 70 micrometers (0.07 mm), though hair ranges from roughly 17 to 180." },
    { q: "How cold can a hibernating arctic ground squirrel’s body get?", h: "Deep in winter torpor.", u: "°F", m: "Temperature", k: "temp", a: 26.8, x: "About 26.8°F (−2.9°C), below freezing, yet its blood stays liquid by supercooling." },
    { q: "How deep is Lake Baikal?", h: "The world’s deepest lake, in Siberia.", u: "ft", m: "Depth", k: "length", a: 5387, x: "About 5,387 ft (1,642 m). It holds about a fifth of the world’s unfrozen fresh water." },
    { q: "How tall is Angel Falls?", h: "The world’s tallest waterfall, in Venezuela.", u: "ft", m: "Height", k: "height", a: 3212, x: "3,212 ft (979 m), so tall that much of the water turns to mist before it lands." },
    { q: "How much does a blue whale’s heart weigh?", h: "The largest heart ever measured.", u: "lb", m: "Weight", k: "other", a: 400, x: "About 400 lb (180 kg), measured from a whale that washed up in Canada in 2014." },
    { q: "How tall was Zeng Jinlian, the tallest woman ever recorded?", h: "China, measured in the early 1980s.", u: "cm", m: "Height", k: "height", a: 248, x: "About 248 cm (8 ft 1.75 in)." },
    { q: "How tall was Chandra Bahadur Dangi, the shortest adult ever verified?", h: "Nepal, measured in 2012.", u: "in", m: "Height", k: "height", a: 21.5, x: "21.5 inches (54.6 cm)." },
    { q: "How close did Mars come to Earth in 2003?", h: "Its closest pass in about 60,000 years.", u: "mi", m: "Distance", k: "length", log: true, a: 34650000, x: "About 34.65 million miles (55.76 million km). It won’t come that close again until 2287." },
    { q: "How wide is the Sun?", h: "Its diameter.", u: "mi", m: "Diameter", k: "length", log: true, a: 865000, x: "About 865,000 miles, wide enough to line up 109 Earths across it." },
    { q: "How far away is the nearest star after the Sun?", h: "Proxima Centauri.", u: "light-years", m: "Distance", k: "length", a: 4.24, x: "About 4.24 light-years, or roughly 25 trillion miles." },
    { q: "How hot is the core of the Sun?", h: "Where fusion happens.", u: "°F", m: "Temperature", k: "temp", a: 27000000, x: "About 27 million °F (15 million °C)." },
    { q: "How cold is liquid helium?", h: "Boiling in a lab dewar.", u: "°F", m: "Temperature", k: "temp", a: -452.1, x: "−452.1°F (4.2 K), just 7.6 degrees above absolute zero." },
    { q: "How loud was the 1883 Krakatoa eruption, 100 miles away?", h: "The loudest sound in recorded history.", u: "dB", m: "Loudness", k: "other", a: 172, x: "About 172 dB at 100 miles, and it was heard nearly 3,000 miles away." },
    { q: "How much did the heaviest person ever recorded weigh?", h: "Jon Brower Minnoch, at his peak.", u: "lb", m: "Weight", k: "other", a: 1400, x: "An estimated 1,400 lb (635 kg), mostly fluid retention." },
    { q: "How big was the Cullinan, the largest gem diamond ever found?", h: "Rough stone, South Africa, 1905.", u: "carats", m: "Weight", k: "other", a: 3106.75, x: "3,106.75 carats (about 1.4 lb). Pieces of it sit in the British Crown Jewels." },
    { q: "How much does the Eiffel Tower weigh?", h: "The whole structure.", u: "tonnes", m: "Weight", k: "other", a: 10100, x: "About 10,100 tonnes, including about 7,300 tonnes of iron." },
    { q: "How long is a day on Jupiter?", h: "One full rotation.", u: "hours", m: "Time", k: "other", a: 9.9, x: "About 9.9 hours, the shortest day of any planet." },
    { q: "How long did Armstrong and Aldrin walk on the Moon?", h: "Apollo 11’s moonwalk, 1969.", u: "min", m: "Time", k: "other", a: 151, x: "About 2 hours 31 minutes outside the lander." },
    { q: "How long can a total solar eclipse last at most?", h: "Totality, from one spot on Earth.", u: "min", m: "Time", k: "other", a: 7.5, x: "About 7.5 minutes at most; many last only 2–3 minutes." },
    { q: "How fast is the fastest human-made object?", h: "NASA’s Parker Solar Probe, 2024.", u: "mph", m: "Speed", k: "other", log: true, a: 430000, x: "About 430,000 mph (692,000 km/h) as it swung past the Sun." },
    { q: "How slow can a diving blue whale’s heart beat?", h: "Measured on a feeding dive.", u: "bpm", m: "Heart rate", k: "other", a: 2, x: "As few as 2 beats per minute, recorded by Stanford researchers in 2019." },
    { q: "How fast can a hummingbird’s heart beat?", h: "A blue-throated hummingbird, at its peak.", u: "bpm", m: "Heart rate", k: "other", a: 1260, x: "About 1,260 beats per minute, around 20 every second." },
    { q: "How tall was the tallest sunflower ever recorded?", h: "Grown in Germany, 2014.", u: "ft", m: "Height", k: "height", a: 30.1, x: "30 ft 1 in, grown by Hans-Peter Schiffer." },
    { q: "How much does a typical puffy cumulus cloud weigh?", h: "All the water droplets in it.", u: "lb", m: "Weight", k: "other", log: true, a: 1100000, x: "About 1.1 million lb, per a U.S. Geological Survey estimate. It floats because the drops are spread out." },
    { q: "How much water pressure is there at the bottom of the Mariana Trench?", h: "Challenger Deep.", u: "psi", m: "Pressure", k: "other", a: 16000, x: "About 16,000 psi (1,086 bar), more than 1,000 times the pressure at sea level." },
    { q: "How tall is Mauna Kea, measured from its base on the sea floor?", h: "Hawaii’s tallest volcano.", u: "ft", m: "Height", k: "height", a: 33500, x: "About 33,500 ft, taller than Everest from base to peak." },
    { q: "At what temperature does seawater freeze?", h: "Ordinary ocean water.", u: "°F", m: "Temperature", k: "temp", a: 28.4, x: "About 28.4°F (−2°C); salt gets in the way of ice crystals." },
    { q: "At what temperature does mercury freeze?", h: "The metal in old thermometers.", u: "°F", m: "Temperature", k: "temp", a: -37.9, x: "−37.9°F, which is why polar explorers used alcohol thermometers." },
    { q: "How hot is Earth’s inner core?", h: "About 3,200 miles beneath your feet.", u: "°F", m: "Temperature", k: "temp", a: 9800, x: "About 9,800°F (5,400°C), yet it stays solid under crushing pressure." },
    { q: "How cold is the coldest snow surface ever measured on Earth?", h: "Satellite data, East Antarctica.", u: "°F", m: "Temperature", k: "temp", a: -144, x: "About −144°F (−98°C), measured from space in shallow hollows on the ice sheet." }
  ]}
];
